development:
  adapter: redis
  url: redis://localhost:6379
  channel_prefix: opto_logs_development

test:
  adapter: test

production:
  adapter: redis
  url: redis://192.168.82.3:6379
  channel_prefix: opto_logs_production
